source :rubygems
gem "sinatra", "1.3.2"
gem "sinatra-contrib", "1.3.1"
gem 'json', '1.7.3'

group :test do
  gem "rspec", "2.7.0"
  gem "mocha", "0.10.0"
  gem "resque_spec", "0.9.2"
  gem "webrat", "0.7.3"
  gem "foreman", "~> 0.46.0"
end
