jslint:
  options:
    continue:   false     # true, if the continuation statement should be tolerated
    debug:      false     # true, if debugger statements should be allowed
    eqeq:       false     # true, if == should be allowed
    es5:        true      # true, if ES5 syntax should be allowed
    evil:       false     # true, if eval should be allowed
    forin:      false     # true, if for in statements need not filter
    newcap:     false     # true, if constructor names capitalization is ignored
    nomen:      true      # true, if names may have dangling _
    on:         false     # true, if HTML event handlers should be allowed
    plusplus:   true      # true, if increment/decrement should be allowed
    regexp:     false     # true, if the . should be allowed in regexp literals
    undef:      false     # true, if variables can be declared out of order
    unparam:    false     # true, if unused parameters should be tolerated
    sloppy:     false     # true, if the 'use strict'; pragma is optional
    stupid:     false     # true, if really stupid practices are tolerated
    vars:       false     # true, if multiple var statements per function should be allowed
    white:      false     # true, if sloppy whitespace is tolerated

    maxlen:     120       # the maximum length of a source line
    indent:     4         # the indentation factor
    maxerr:     10        # the maximum number of errors to allow
    passfail:   false     # true, if the scan should stop on first error

